import type { Locale } from '../config';

// Strings for /projects/mbti-app. Section headings shared with other project
// pages (overview, tech stack, outcomes, learnings, links, ...) live in common.ts.
const ja = {
  title: 'MBTI × 生成AI体験アプリ',
  description:
    '北村健紀が開発した MBTI × 生成AI 体験アプリ。物語形式の診断で無意識の価値観を引き出す、Ruby on Rails + OpenAI API のWebアプリ。',
  heading: 'MBTI × 生成AI体験アプリ',
  period: '2024年6月〜2024年8月（3ヵ月）',
  overview:
    'MBTI診断と生成AIを組み合わせた体験型Webアプリケーション。ユーザーの回答からMBTIタイプを推定し、AIが音楽・写真・ストーリーなどを自動生成して体験として提供する。企画・開発・公開まで、すべて個人で担当。',
  problem: {
    heading: '解決しようとした課題',
    intro: '従来のMBTI診断アプリにあった課題：',
    items: [
      '• 質問同士の文脈がなく、ユーザーが回答に迷いやすい',
      '• 用意された質問に自分を当てはめる形式では、本来の性格を正確に測りにくい',
    ],
  },
  features: {
    heading: '工夫した点',
    story: {
      heading: '「物語モード」の実装',
      items: [
        '• ユーザーは「ホラー」「アドベンチャー」「ミステリー」、完全オリジナルの「クリエイター」などの世界を選択',
        '• AIが生成する状況に応じて選択肢を選び続けることで、無意識の価値観や行動パターンが自然に表に出るようにした',
      ],
    },
    result: {
      heading: '診断結果の出し方',
      body: '物語の内容も加味してMBTIタイプを出力し、従来より納得感のある結果になるようにした',
    },
    technical: {
      heading: '技術的な工夫',
      items: [
        '• OpenAI APIの呼び出しを共通化し、エラー時に別ルートで処理する仕組みを実装',
        '• 前の質問の内容や何問目かによって物語の段階を変更し、AIの出力の質を向上',
      ],
    },
  },
  outcome: '診断結果に物語体験を加えることで、ユーザーが自分の性格をより自然に受け止めやすい形にできた。',
  learning:
    'ユーザー体験を設計する際、「どんなUIを作るか」だけでなく、「どうすれば自然に行動や本音を引き出せるか」を考えることの重要性を実感した。',
};

type MbtiDict = typeof ja;

const en: MbtiDict = {
  title: 'MBTI × Generative AI Experience App',
  description:
    'An MBTI × generative AI experience app built by Tatsuki Kitamura. A Ruby on Rails + OpenAI API web app whose story-driven assessment draws out unconscious values.',
  heading: 'MBTI × Generative AI Experience App',
  period: 'Jun 2024 — Aug 2024 (3 months)',
  overview:
    "An experiential web application that combines an MBTI assessment with generative AI. It estimates the user's MBTI type from their answers, then has the AI generate music, images and stories to deliver the result as an experience. I handled everything from planning to development and release on my own.",
  problem: {
    heading: 'The problem I set out to solve',
    intro: 'Issues with conventional MBTI assessment apps:',
    items: [
      '• The questions have no context linking them, so users often struggle to answer',
      '• Fitting yourself into pre-written questions makes it hard to measure your true personality accurately',
    ],
  },
  features: {
    heading: 'What I put thought into',
    story: {
      heading: 'Implementing "Story Mode"',
      items: [
        '• Users choose a world such as "Horror", "Adventure", "Mystery", or the fully original "Creator"',
        "• By continually choosing options in situations generated by the AI, users' unconscious values and behaviour patterns surface naturally",
      ],
    },
    result: {
      heading: 'How results are produced',
      body: 'The MBTI type is derived with the content of the story taken into account, making the result feel more convincing than a conventional assessment',
    },
    technical: {
      heading: 'Technical details',
      items: [
        '• Centralised the OpenAI API calls and built a mechanism that handles errors through a separate route',
        "• Changed the stage of the story according to the previous answers and the question number, improving the quality of the AI's output",
      ],
    },
  },
  outcome:
    'By adding a story experience to the assessment result, users can accept their own personality in a more natural way.',
  learning:
    'I came to appreciate that designing a user experience is not just about "what UI to build" but about "how to draw out behaviour and honest feelings naturally".',
};

const zh: MbtiDict = {
  title: 'MBTI × 生成式 AI 体验应用',
  description:
    '北村健纪开发的 MBTI × 生成式 AI 体验应用。通过故事形式的测试引出潜意识中的价值观，基于 Ruby on Rails + OpenAI API 的 Web 应用。',
  heading: 'MBTI × 生成式 AI 体验应用',
  period: '2024年6月〜2024年8月（3个月）',
  overview:
    '将 MBTI 测试与生成式 AI 结合的体验型 Web 应用。根据用户的回答推断 MBTI 类型，再由 AI 自动生成音乐、照片、故事等内容，作为一种体验提供给用户。从策划、开发到发布，全部由我一人完成。',
  problem: {
    heading: '想要解决的问题',
    intro: '传统 MBTI 测试应用存在的问题：',
    items: [
      '• 问题之间缺乏上下文，用户容易在作答时犹豫不决',
      '• 把自己套进预设问题的形式，难以准确测出真实的性格',
    ],
  },
  features: {
    heading: '下功夫的地方',
    story: {
      heading: '“故事模式”的实现',
      items: [
        '• 用户可以选择“恐怖”“冒险”“悬疑”，以及完全原创的“创作者”等世界观',
        '• 通过在 AI 生成的情境中不断做出选择，让潜意识中的价值观和行为模式自然地显露出来',
      ],
    },
    result: {
      heading: '测试结果的生成方式',
      body: '在输出 MBTI 类型时同时考虑故事内容，使结果比传统方式更令人信服',
    },
    technical: {
      heading: '技术上的巧思',
      items: [
        '• 将 OpenAI API 的调用统一封装，并实现了出错时通过其他路径处理的机制',
        '• 根据前一个问题的内容和当前题号改变故事的阶段，提高 AI 输出的质量',
      ],
    },
  },
  outcome: '通过在测试结果中加入故事体验，让用户能以更自然的方式接受自己的性格。',
  learning:
    '深刻体会到，在设计用户体验时，不仅要考虑“做什么样的 UI”，更要思考“如何自然地引出用户的行为和真实想法”。',
};

const ko: MbtiDict = {
  title: 'MBTI × 생성형 AI 체험 앱',
  description:
    '키타무라 타츠키가 개발한 MBTI × 생성형 AI 체험 앱. 이야기 형식의 진단으로 무의식적인 가치관을 끌어내는 Ruby on Rails + OpenAI API 웹 앱.',
  heading: 'MBTI × 생성형 AI 체험 앱',
  period: '2024년 6월〜2024년 8월 (3개월)',
  overview:
    'MBTI 진단과 생성형 AI를 결합한 체험형 웹 애플리케이션. 사용자의 답변으로부터 MBTI 유형을 추정하고, AI가 음악·사진·스토리 등을 자동 생성하여 하나의 체험으로 제공한다. 기획·개발·공개까지 모두 혼자 담당.',
  problem: {
    heading: '해결하려고 한 과제',
    intro: '기존 MBTI 진단 앱에 있던 과제:',
    items: [
      '• 질문 사이에 맥락이 없어 사용자가 답변에 망설이기 쉽다',
      '• 준비된 질문에 자신을 끼워 맞추는 형식으로는 본래의 성격을 정확히 측정하기 어렵다',
    ],
  },
  features: {
    heading: '고민한 점',
    story: {
      heading: '"이야기 모드" 구현',
      items: [
        '• 사용자는 "호러", "어드벤처", "미스터리", 완전 오리지널인 "크리에이터" 등의 세계를 선택',
        '• AI가 생성하는 상황에 따라 계속 선택지를 고르게 함으로써, 무의식적인 가치관과 행동 패턴이 자연스럽게 드러나도록 했다',
      ],
    },
    result: {
      heading: '진단 결과를 내는 방식',
      body: '이야기의 내용까지 반영해 MBTI 유형을 출력하여, 기존보다 납득감 있는 결과가 되도록 했다',
    },
    technical: {
      heading: '기술적인 고민',
      items: [
        '• OpenAI API 호출을 공통화하고, 오류 시 다른 경로로 처리하는 구조를 구현',
        '• 이전 질문의 내용과 몇 번째 질문인지에 따라 이야기의 단계를 바꾸어 AI 출력의 품질을 향상',
      ],
    },
  },
  outcome:
    '진단 결과에 이야기 체험을 더함으로써, 사용자가 자신의 성격을 더 자연스럽게 받아들이기 쉬운 형태로 만들 수 있었다.',
  learning:
    '사용자 경험을 설계할 때 "어떤 UI를 만들 것인가"뿐만 아니라 "어떻게 하면 자연스럽게 행동과 속마음을 끌어낼 수 있을까"를 생각하는 것의 중요성을 실감했다.',
};

const mbti: Record<Locale, MbtiDict> = { ja, en, zh, ko };
export default mbti;
